name: Tyr CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: JDK ${{matrix.java-version}} JVM build and tests
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        java-version: [11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: actions/setup-java@v1
      name: Set up JDK ${{ matrix.java-version }}
      with:
        java-version: ${{ matrix.java-version }}

    - name: Build with Maven
      run: mvn clean install

